#!/bin/sh

# usage: scullc_unload
# This script unloads scullc devices previously loaded using the scullc_load
# script.

module="scullc"
device="scullc"

# Invoke rmmod with all arguments we got.
/sbin/rmmod $module $* || exit 1

# Remove stale nodes.
rm -f /dev/${device} /dev/${device}[0-3]
