#!/bin/sh

# usage: scullpg_unload
# This script unloads scullpg devices previously loaded using the scullpg_load
# script.

module="scullpg"
device="scullpg"

# Invoke rmmod with all arguments we got.
/sbin/rmmod $module $* || exit 1

# Remove stale nodes.
rm -f /dev/${device} /dev/${device}[0-3]
