#!/bin/sh

# usage: faulty_load
# This script loads the faulty module.

module="faulty"
device="faulty"
mode="664"

# Invoke insmod with all arguments we got and use a pathname, as insmod
# doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# Retrieve major number.
# The awk command given in ldd3 book is buggy. The command below works and was
# taken from https://stackoverflow.com/questions/13951598/meaning-of-this-shell-script-line-with-awk
major=$(awk -v mod=$module '$2==mod{print $1}' /proc/devices)

# Remove stale nodes and replace them. We don't deal with group permissions
# here but if your emulator image has admin groups, you need to set the group
# permissions on the devices.
rm -f /dev/${device}0
mknod /dev/${device}0 c $major 0
ln -sf ${device}0 /dev/${device}
chmod $mode  /dev/${device}0
