#!/bin/sh

# usage: scullv_unload
# This script unloads scullv devices previously loaded using the scullv_load
# script.

module="scullv"
device="scullv"

# Invoke rmmod with all arguments we got.
/sbin/rmmod $module $* || exit 1

# Remove stale nodes.
rm -f /dev/${device} /dev/${device}[0-3]
