#!/bin/sh

# usage: scullp_unload
# This script unloads scullp devices previously loaded using the scullp_load
# script.

module="scullp"
device="scullpipe"

# Invoke rmmod with all arguments we got.
/sbin/rmmod $module $* || exit 1

# Remove stale nodes.
rm -f /dev/${device} /dev/${device}[0-3]
