#!/bin/sh

# usage: scullp_load [MODULE_PARAMS]...
# This script loads scullp[0-3]. The script accepts zero or more module
# parameters. For example,
#     ./scullp_load scull_p_major=248 scull_p_minor=0 scull_p_nr_devs=4 \
#     scull_p_buffer=4000

module="scullp"
device="scullpipe"
mode="664"

# Invoke insmod with all arguments we got and use a pathname, as insmod
# doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# Retrieve major number.
# The awk command given in ldd3 book is buggy. The command below works and was
# taken from https://stackoverflow.com/questions/13951598/meaning-of-this-shell-script-line-with-awk
major=$(awk -v mod=$module '$2==mod{print $1}' /proc/devices)

# Remove stale nodes and replace them. We don't deal with group permissions
# here but if your emulator image has admin groups, you need to set the group
# permissions on the devices.
rm -f /dev/${device}[0-3]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
ln -sf ${device}0 /dev/${device}
chmod $mode /dev/${device}[0-3]
